import {
  ClientMenuIcon,
  CommentMenuIcon,
  ComplaintMenuIcon,
  ConsultMenuIcon,
  ContactMenuIcon,
  CourierMenuIcon,
  DashboardMenuIcon,
  DiscountMenuIcon,
  LaboratoryMenuIcon,
  MedicalMenuIcon,
  MonitoringMenuIcon,
  OrderMenuIcon,
  PharmacyMenuIcon,
  PostMenuIcon,
  ProductMenuIcon,
  SettingMenuIcon,
  SmsMenuIcon,
  SurveyMenuIcon,
  UserMenuIcon,
  VersionMenuIcon,
} from '../../../assets/pb-icons';

export const MenuIcons = {
  Dashboard: <DashboardMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Users: <UserMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Clients: <ClientMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Financials: <OrderMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Discounts: <DiscountMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Products: <ProductMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Pharmacies: <PharmacyMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Consults: <ConsultMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Laboratories: <LaboratoryMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Medical: <MedicalMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Couriers: <CourierMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  SMS: <SmsMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Posts: <PostMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Complaints: <ComplaintMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Survey: <SurveyMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Comments: <CommentMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Contacts: <ContactMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Monitoring: <MonitoringMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Versions: <VersionMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
  Settings: <SettingMenuIcon className={'w-5 h-5 min-h-5 min-w-5'} />,
};
