export const catalogRoutes = {
  'route.catalog.categories.index': '/catalog/categories',
  'route.catalog.categories.create': '/catalog/categories/create',
  'route.catalog.categories.update': '/catalog/categories/[id]',
  'api.catalog.categories.index': 'categories',
  'api.catalog.categories.show': 'categories/[id]',

  'route.catalog.products.index': '/catalog/products',
  'route.catalog.products.create': '/catalog/products/create',
  'route.catalog.products.update': '/catalog/products/[id]',
  'api.catalog.products.index': 'products',
  'api.catalog.products.show': 'products/[id]',

  'route.catalog.recurring-profiles.index': '/catalog/recurring-profiles',
  'route.catalog.recurring-profiles.create': '/catalog/recurring-profiles/create',
  'route.catalog.recurring-profiles.update': '/catalog/recurring-profiles/[id]',

  'route.catalog.filters.index': '/catalog/filters',
  'route.catalog.filters.create': '/catalog/filters/create',
  'route.catalog.filters.update': '/catalog/filters/[id]',
  'api.catalog.filters.index': 'filters',
  'api.catalog.filters.show': 'filters/[id]',
  'api.catalog.filter-description.delete': 'filter-descriptions/[id]',

  'route.catalog.attributes.index': '/catalog/attributes',
  'route.catalog.attributes.create': '/catalog/attributes/create',
  'route.catalog.attributes.update': '/catalog/attributes/[id]',
  'api.catalog.attributes.index': 'attributes',
  'api.catalog.attributes.show': 'attributes/[id]',
  'api.catalog.attribute-description.delete': 'attribute-descriptions/[id]',

  'route.catalog.attribute-groups.index': '/catalog/attribute-groups',
  'route.catalog.attribute-groups.create': '/catalog/attribute-groups/create',
  'route.catalog.attribute-groups.update': '/catalog/attribute-groups/[id]',
  'api.catalog.attribute-groups.index': 'attribute-groups',
  'api.catalog.attribute-groups.show': 'attribute-groups/[id]',

  'route.catalog.manufacturers.index': '/catalog/manufacturers',
  'route.catalog.manufacturers.create': '/catalog/manufacturers/create',
  'route.catalog.manufacturers.update': '/catalog/manufacturers/[id]',
  'api.catalog.manufacturers.index': 'manufacturers',
  'api.catalog.manufacturers.show': 'manufacturers/[id]',

  'route.catalog.downloads.index': '/catalog/downloads',
  'route.catalog.downloads.create': '/catalog/downloads/create',
  'route.catalog.downloads.update': '/catalog/downloads/[id]',

  'route.catalog.reviews.index': '/catalog/reviews',
  'route.catalog.reviews.create': '/catalog/reviews/create',
  'route.catalog.reviews.update': '/catalog/reviews/[id]',

  'route.catalog.information.index': '/catalog/information',
  'route.catalog.information.create': '/catalog/information/create',
  'route.catalog.information.update': '/catalog/information/[id]',

  'route.catalog.options.index': '/catalog/options',
  'route.catalog.options.create': '/catalog/options/create',
  'route.catalog.options.update': '/catalog/options/[id]',
  'api.catalog.options.index': 'options',
  'api.catalog.options.show': 'options/[id]',
  'api.catalog.option-description.delete': 'option-descriptions/[id]',

  'route.catalog.option-values.index': '/catalog/option-values',
  'route.catalog.option-values.create': '/catalog/option-values/create',
  'route.catalog.option-values.update': '/catalog/option-values/[id]',
  'api.catalog.option-values.index': 'option-values',
  'api.catalog.option-values.show': 'option-values/[id]',
  'api.catalog.option-values-description.delete': 'option-value-descriptions/[id]',

  'route.catalog.filter-groups.index': '/catalog/filter-groups',
  'route.catalog.filter-groups.create': '/catalog/filter-groups/create',
  'route.catalog.filter-groups.update': '/catalog/filter-groups/[id]',
  'api.catalog.filter-groups.index': 'filter-groups',
  'api.catalog.filter-groups.show': 'filter-groups/[id]',

  'route.catalog.recurrings.index': '/catalog/recurrings',
  'route.catalog.recurrings.create': '/catalog/recurrings/create',
  'route.catalog.recurrings.update': '/catalog/recurrings/[id]',
  'api.catalog.recurrings.index': 'recurrings',
  'api.catalog.recurrings.show': 'recurrings/[id]',
  'api.catalog.recurring-descriptions.delete': 'recurring-descriptions/[id]',

  'route.catalog.orders.index': '/catalog/orders',
  'route.catalog.orders.create': '/catalog/orders/create',
  'route.catalog.orders.update': '/catalog/orders/[id]',
  'api.catalog.orders.index': 'orders',
  'api.catalog.orders.show': 'orders/[id]',
  'api.catalog.order-status.delete': 'order-statuses/[id]',
  'api.catalog.order-history.delete': 'order-histories/[id]',
  'api.catalog.order-option.delete': 'order-options/[id]',
  'api.catalog.order-product.delete': 'order-products/[id]',
  'api.catalog.order-recurring.delete': 'order-recurrings/[id]',
  'api.catalog.order-shipment.delete': 'order-shipments/[id]',
  'api.catalog.order-total.delete': 'order-totals/[id]',
  'api.catalog.order-voucher.delete': 'order-vouchers/[id]',
};
