export const localisationsRoutes = {
  'route.localisations.store-location.index': '/localisations/store-location',
  'route.localisations.store-location.create': '/localisations/store-location/create',
  'route.localisations.store-location.update': '/localisations/store-location/[id]',

  'route.localisations.languages.index': '/localisations/languages',
  'route.localisations.languages.create': '/localisations/languages/create',
  'route.localisations.languages.update': '/localisations/languages/[id]',
  'api.localisations.languages.index': 'languages',
  'api.localisations.languages.show': 'languages/[id]',

  'route.localisations.currencies.index': '/localisations/currencies',
  'route.localisations.currencies.create': '/localisations/currencies/create',
  'route.localisations.currencies.update': '/localisations/currencies/[id]',
  'api.localisations.currencies.index': 'currencies',
  'api.localisations.currencies.show': 'currencies/[id]',

  'route.localisations.countries.index': '/localisations/countries',
  'route.localisations.countries.create': '/localisations/countries/create',
  'route.localisations.countries.update': '/localisations/countries/[id]',
  'api.localisations.countries.index': 'countries',
  'api.localisations.countries.show': 'countries/[id]',

  'route.localisations.zones.index': '/localisations/zones',
  'route.localisations.zones.create': '/localisations/zones/create',
  'route.localisations.zones.update': '/localisations/zones/[id]',
  'api.localisations.zones.index': 'zones',
  'api.localisations.zones.show': 'zones/[id]',

  'route.localisations.geoZones.index': '/localisations/geo-zones',
  'route.localisations.geoZones.create': '/localisations/geo-zones/create',
  'route.localisations.geoZones.update': '/localisations/geo-zones/[id]',
  'api.localisations.geoZones.index': 'geo-zones',
  'api.localisations.geoZones.show': 'geo-zones/[id]',

  'route.localisations.lengthClasses.index': '/localisations/length-classes',
  'route.localisations.lengthClasses.create': '/localisations/length-classes/create',
  'route.localisations.lengthClasses.update': '/localisations/length-classes/[id]',
  'api.localisations.lengthClasses.index': 'length-classes',
  'api.localisations.lengthClasses.show': 'length-classes/[id]',

  'route.localisations.lengthClassDescriptions.index': '/localisations/length-class-descriptions',
  'route.localisations.lengthClassDescriptions.create': '/localisations/length-class-descriptions/create',
  'route.localisations.lengthClassDescriptions.update': '/localisations/length-class-descriptions/[id]',
  'api.localisations.lengthClassDescriptions.index': 'length-class-descriptions',
  'api.localisations.lengthClassDescriptions.show': 'length-class-descriptions/[id]',

  'route.localisations.weightClasses.index': '/localisations/weight-classes',
  'route.localisations.weightClasses.create': '/localisations/weight-classes/create',
  'route.localisations.weightClasses.update': '/localisations/weight-classes/[id]',
  'api.localisations.weightClasses.index': 'weight-classes',
  'api.localisations.weightClasses.show': 'weight-classes/[id]',

  'route.localisations.weightClassDescriptions.index': '/localisations/weight-class-descriptions',
  'route.localisations.weightClassDescriptions.create': '/localisations/weight-class-descriptions/create',
  'route.localisations.weightClassDescriptions.update': '/localisations/weight-class-descriptions/[id]',
  'api.localisations.weightClassDescriptions.index': 'weight-class-descriptions',
  'api.localisations.weightClassDescriptions.show': 'weight-class-descriptions/[id]',

  'route.localisations.locations.index': '/localisations/locations',
  'route.localisations.locations.create': '/localisations/locations/create',
  'route.localisations.locations.update': '/localisations/locations/[id]',
  'api.localisations.locations.index': 'locations',
  'api.localisations.locations.show': 'locations/[id]',

  'route.localisations.stores.index': '/localisations/stores',
  'route.localisations.stores.create': '/localisations/stores/create',
  'route.localisations.stores.update': '/localisations/stores/[id]',
  'api.localisations.stores.index': 'stores',
  'api.localisations.stores.show': 'stores/[id]',

  'route.localisations.stockStatuses.index': '/localisations/stock-statuses',
  'route.localisations.stockStatuses.create': '/localisations/stock-statuses/create',
  'route.localisations.stockStatuses.update': '/localisations/stock-statuses/[id]',
  'api.localisations.stockStatuses.index': 'stock-statuses',
  'api.localisations.stockStatuses.show': 'stock-statuses/[id]',

  'route.localisations.taxClasses.index': '/localisations/tax-classes',
  'route.localisations.taxClasses.create': '/localisations/tax-classes/create',
  'route.localisations.taxClasses.update': '/localisations/tax-classes/[id]',
  'api.localisations.taxClasses.index': 'tax-classes',
  'api.localisations.taxClasses.show': 'tax-classes/[id]',

  'route.localisations.taxRates.index': '/localisations/tax-rates',
  'route.localisations.taxRates.create': '/localisations/tax-rates/create',
  'route.localisations.taxRates.update': '/localisations/tax-rates/[id]',
  'api.localisations.taxRates.index': 'tax-rates',
  'api.localisations.taxRates.show': 'tax-rates/[id]',

  'route.localisations.settings.index': '/localisations/settings',
  'route.localisations.settings.create': '/localisations/settings/create',
  'route.localisations.settings.update': '/localisations/settings/[id]',
  'api.localisations.settings.index': 'settings',
  'api.localisations.settings.show': 'settings/[id]',

  'route.localisations.uploads.index': '/localisations/uploads',
  'route.localisations.uploads.create': '/localisations/uploads/create',
  'route.localisations.uploads.update': '/localisations/uploads/[id]',
  'api.localisations.uploads.index': 'uploads',
  'api.localisations.uploads.show': 'uploads/[id]',

  'route.localisations.shippingCouriers.index': '/localisations/shipping-couriers',
  'route.localisations.shippingCouriers.create': '/localisations/shipping-couriers/create',
  'route.localisations.shippingCouriers.update': '/localisations/shipping-couriers/[id]',
  'api.localisations.shippingCouriers.index': 'shipping-couriers',
  'api.localisations.shippingCouriers.show': 'shipping-couriers/[id]',

  'route.localisations.statistics.index': '/localisations/statistics',
  'route.localisations.statistics.create': '/localisations/statistics/create',
  'route.localisations.statistics.update': '/localisations/statistics/[id]',
  'api.localisations.statistics.index': 'statistics',
  'api.localisations.statistics.show': 'statistics/[id]',
};
