export const DIVIDER_COLOR = {
  inherit: 'border-inherit',
  primary: 'border-primary-100',
  secondary: 'border-secondary-100',
  tertiary: 'border-tertiary-100',
  control: 'border-control-100',
  success: 'border-success-100',
  info: 'border-info-100',
  warning: 'border-warning-100',
  danger: 'border-danger-100',
  slate: 'border-slate-100',
  zinc: 'border-zinc-100',
  neutral: 'border-neutral-100',
  stone: 'border-stone-100',
  red: 'border-red-100',
  orange: 'border-orange-100',
  amber: 'border-amber-100',
  yellow: 'border-yellow-100',
  lime: 'border-lime-100',
  green: 'border-green-100',
  emerald: 'border-emerald-100',
  teal: 'border-teal-100',
  cyan: 'border-cyan-100',
  sky: 'border-sky-100',
  blue: 'border-blue-100',
  indigo: 'border-indigo-100',
  violet: 'border-violet-100',
  purple: 'border-purple-100',
  fuchsia: 'border-fuchsia-100',
  pink: 'border-pink-100',
  rose: 'border-rose-100',
};

export const BULLET_COLOR = {
  inherit: 'text-inherit',
  primary: 'before:bg-primary',
  secondary: 'before:bg-secondary',
  tertiary: 'before:bg-tertiary',
  control: 'before:bg-control',
  success: 'before:bg-success',
  info: 'before:bg-info',
  warning: 'before:bg-warning',
  danger: 'before:bg-danger',
  slate: 'before:bg-slate-500',
  zinc: 'before:bg-zinc-500',
  neutral: 'before:bg-neutral-500',
  stone: 'before:bg-stone-500',
  red: 'before:bg-red-500',
  orange: 'before:bg-orange-500',
  amber: 'before:bg-amber-500',
  yellow: 'before:bg-yellow-500',
  lime: 'before:bg-lime-500',
  green: 'before:bg-green-500',
  emerald: 'before:bg-emerald-500',
  teal: 'before:bg-teal-500',
  cyan: 'before:bg-cyan-500',
  sky: 'before:bg-sky-500',
  blue: 'before:bg-blue-500',
  indigo: 'before:bg-indigo-500',
  violet: 'before:bg-violet-500',
  purple: 'before:bg-purple-500',
  fuchsia: 'before:bg-fuchsia-500',
  pink: 'before:bg-pink-500',
  rose: 'before:bg-rose-500',
};

export const BULLET_SHAPE = {
  circle: 'before:rounded-full',
  square: 'before:rounded',
};
