export const COLORS = {
  black: 'accent-black hover:accent-black',
  primary: 'border border-control-500 hover:border-control-700 checked:bg-primary checked:border-primary checked:hover:bg-primary-700 checked:hover:border-primary-700 active:border-primary-light',
  info: 'border border-control-500 hover:border-control-700 checked:bg-info checked:border-info checked:hover:bg-info-700 checked:hover:border-info-700 active:border-info-light',
  danger: 'border border-control-500 hover:border-control-700 checked:bg-danger checked:border-danger checked:hover:bg-danger-700 checked:hover:border-danger-700 active:border-danger-light',
  warning: 'border border-control-500 hover:border-control-700 checked:bg-warning checked:border-warning checked:hover:bg-warning-700 checked:hover:border-warning-700 active:border-warning-light',
  secondary: 'border border-control-500 hover:border-control-700 checked:bg-secondary checked:border-secondary checked:hover:bg-secondary-700 checked:hover:border-secondary-700 active:border-secondary-light',
  control: 'border border-control-500 hover:border-control-700 checked:bg-control checked:border-control checked:hover:bg-control-700 checked:hover:border-control-700 active:border-control-light',
  tertiary: 'border border-control-500 hover:border-control-700 checked:bg-tertiary checked:border-tertiary checked:hover:bg-tertiary-700 checked:hover:border-tertiary-700 active:border-tertiary-light',
  success: 'border border-control-500 hover:border-control-700 checked:bg-success checked:border-success checked:hover:bg-success-700 checked:hover:border-success-700 active:border-success-light',
  inherit: 'border-transparent hover:border-control-700',
  slate: 'border border-control-500 hover:border-control-700 checked:bg-slate-500 checked:hover:bg-slate-700 checked:hover:border-slate-700 checked:border-slate-500 active:border-slate-300',
  zinc: 'border border-control-500 hover:border-control-700 checked:bg-zinc-500 checked:hover:bg-zinc-700 checked:hover:border-zinc-700 checked:border-zinc-500 active:border-zinc-300',
  neutral: 'border border-control-500 hover:border-control-700 checked:bg-neutral-500 checked:hover:bg-natural-700 checked:hover:border-natural-700 checked:border-neutral-500 active:border-neutral-300',
  stone: 'border border-control-500 hover:border-control-700 checked:bg-stone-500 checked:hover:bg-stone-700 checked:hover:border-stone-700 checked:border-stone-500 active:border-stone-300',
  red: 'border border-control-500 hover:border-control-700 checked:bg-red-500 checked:hover:bg-red-700 checked:hover:border-red-700 checked:border-red-500 active:border-red-300',
  orange: 'border border-control-500 hover:border-control-700 checked:bg-orange-500 checked:hover:bg-orange-700 checked:hover:border-orange-700 checked:border-orange-500 active:border-orange-300',
  amber: 'border border-control-500 hover:border-control-700 checked:bg-amber-500 checked:hover:bg-amber-700 checked:hover:border-amber-700 checked:border-amber-500 active:border-amber-300',
  yellow: 'border border-control-500 hover:border-control-700 checked:bg-yellow-500 checked:hover:bg-yellow-700 checked:hover:border-yellow-700 checked:border-yellow-500 active:border-yellow-300',
  lime: 'border border-control-500 hover:border-control-700 checked:bg-lime-500 checked:hover:bg-lime-700 checked:hover:border-lime-700 checked:border-lime-500 active:border-lime-300',
  green: 'border border-control-500 hover:border-control-700 checked:bg-green-500 checked:hover:bg-green-700 checked:hover:border-green-700 checked:border-green-500 active:border-green-300',
  emerald: 'border border-control-500 hover:border-control-700 checked:bg-emerald-500 checked:hover:bg-emerald-700 checked:hover:border-emerald-700 checked:border-emerald-500 active:border-emerald-300',
  teal: 'border border-control-500 hover:border-control-700 checked:bg-teal-500 checked:hover:bg-teal-700 checked:hover:border-teal-700 checked:border-teal-500 active:border-teal-300',
  cyan: 'border border-control-500 hover:border-control-700 checked:bg-cyan-500 checked:hover:bg-cyan-700 checked:hover:border-cyan-700 checked:border-cyan-500 active:border-cyan-300',
  sky: 'border border-control-500 hover:border-control-700 checked:bg-sky-500 checked:hover:bg-sky-700 checked:hover:border-sky-700 checked:border-sky-500 active:border-sky-300',
  blue: 'border border-control-500 hover:border-control-700 checked:bg-blue-500 checked:hover:bg-blue-700 checked:hover:border-blue-700 checked:border-blue-500 active:border-blue-300',
  indigo: 'border border-control-500 hover:border-control-700 checked:bg-indigo-500 checked:hover:bg-indigo-700 checked:hover:border-indigo-700 checked:border-indigo-500 active:border-indigo-300',
  violet: 'border border-control-500 hover:border-control-700 checked:bg-violet-500 checked:hover:bg-violet-700 checked:hover:border-violet-700 checked:border-violet-500 active:border-violet-300',
  purple: 'border border-control-500 hover:border-control-700 checked:bg-purple-500 checked:hover:bg-purple-700 checked:hover:border-purple-700 checked:border-purple-500 active:border-purple-300',
  fuchsia: 'border border-control-500 hover:border-control-700 checked:bg-fuchsia-500 checked:hover:bg-fuchsia-700 checked:hover:border-fuchsia-700 checked:border-fuchsia-500 active:border-fuchsia-300',
  pink: 'border border-control-500 hover:border-control-700 checked:bg-pink-500 checked:hover:bg-pink-700 checked:hover:border-pink-700 checked:border-pink-500 active:border-pink-300',
  rose: 'border border-control-500 hover:border-control-700 checked:bg-rose-500 checked:hover:bg-rose-700 checked:hover:border-rose-700 checked:border-rose-500 active:border-rose-300',
};

export const SIZES = {
  huge: 'h-7 w-7 md:h-7',
  large: 'h-6 w-6 md:h-6',
  medium: 'h-5 w-5 md:h-5',
  small: 'h-4 w-4 md:h-4',
  tiny: 'h-3 w-3 md:h-3',
};

export const CHECK_SIZES = {
  huge: 'h-6 w-6 md:h-6',
  large: 'h-5 w-5 md:h-5',
  medium: 'h-4 w-4 md:h-4',
  small: 'h-3 w-3 md:h-3',
  tiny: 'h-2 w-2 md:h-2',
};
